
services:
  quasar-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "9001:9000"
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]